### ISSUE TITLE
Manual changes in the db for our sponsors displayed on the campaign 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-campaign#33] opened 2017-03-01 19:14 UTC
I'd appreciate it immensly if someone could change this. Here is a quick how-to: https://github.com/rails-girls-summer-of-code/rgsoc-campaign/wiki/Edit-app-database-entries#editing-a-record

 
<img width="617" alt="screen shot 2017-03-01 at 20 10 17" src="https://cloud.githubusercontent.com/assets/1711357/23476496/35f2bbe2-febb-11e6-8b4a-adabf68d9660.png">

- cobots avatar should be this one:  /img/sponsors/cobot_avatar.png
- to change nextclouds avatar the email should be changed to: jan-c.borchardt@nextcloud.com
- heroku's avatar should be this one: /img/sponsors/heroku_avatar.png
- nokia's avatar should be this one: /img/sponsors/nokia_avatar.png
- ableton's avatar should be this one: /img/sponsors/ableton_avatar.png 
- articulate's (kelly meeker donated) avatar should be this one: /img/sponsors/articulate_gravatar.png also the name should be changed to articulate
- wooga's avatar should be this one: /img/sponsors/wooga_avatar.png

**Comment by bitboxer** [comment] 2017-03-01 19:24
I will do this now

**Comment by bitboxer** [comment] 2017-03-01 19:29
@anikalindtner the heroku image is not working, I think it is a photoshop file. Can you fix that? Than the image will work again. The link is already corrected in the database

**Comment by bitboxer** [comment] 2017-03-01 19:31
@anikalindtner should I also rename kelly meeker  to articulate?

**Comment by bitboxer** [comment] 2017-03-01 19:33
Okay, everything done except the rename of kelly meeker. Will do that after it is confirmed that I should rename it.

**Comment by anikalindtner** [comment] 2017-03-01 19:34
@bitboxer yes please, kelly meeker should be articulate. i've fixed heroku's file. 

could you also point eggheads avatar to /img/sponsors/egghead_avatar.png?

**Comment by bitboxer** [comment] 2017-03-01 19:37
Sadly the egghead file is also a photoshop file. And I renamed kelly meeker. Launch Schools logo seems wrong, too.

**Comment by anikalindtner** [comment] 2017-03-01 19:43
yes, there are some missing that i overlooked (you don't have to fix it now, can also leave it for later, since it's my bad)
+ launchschool : /img/sponsors/launchschool_avatar.png. 
+ Also: /apcera_avatar.png

and with the egghead avatar that's super weird. locally it is a png file. i can try to upload it again

**Comment by bitboxer** [comment] 2017-03-01 19:44
Here it is a photoshop file 😢 

<img width="556" alt="screen shot 2017-03-01 at 20 44 07" src="https://cloud.githubusercontent.com/assets/56195/23477918/dcb8e470-febf-11e6-96f2-5c21223da6a4.png">

Will fix the other two now.

**Comment by anikalindtner** [comment] 2017-03-01 19:45
yeah, meh. i've fixed it now, should be .png hopefully now for realzies :crossed_fingers:

**Comment by bitboxer** [comment] 2017-03-01 19:48
Okay, now everything should be fine 👍

**Comment by anikalindtner** [comment] 2017-03-01 19:52
whooooop! thank you so much for fixing all this so quickly 🚀 ✨ 💚

**Comment by anikalindtner** [comment] 2017-03-02 18:59
new todos for whoever has time: 

-basecamps avatar to: /basecamp_gravatar.png
- add turing school: Donation.create package: "Bronze", amount: 1_000_00, add_vat: false, name: "Turing School", twitter_handle: "turingschool", github_handle: "turingschool", display: true, gravatar_url="/img/sponsors/turing_avatar.png"

**Comment by bitboxer** [comment] 2017-03-03 15:16
Done.

**Comment by anikalindtner** [comment] 2017-03-04 10:09
yaay! thank you so much! :tada:

**Comment by anikalindtner** [comment] 2017-03-09 19:53
fresh new sponsors coming in! 

+ [ ] Donation.create package: "Bronze", amount: 1_000_00, add_vat: false, name: "Gitlab", twitter_handle: "Gitlab", github_handle: "gitlabhq", display: true, gravatar_url="/img/sponsors/gitlab_gravatar.png"

+ Donation.create package: "Bronze", amount: 1_000_00, add_vat: false, name: "Spotify", twitter_handle: "Spotify", github_handle: "spotify", display: true, gravatar_url="/img/sponsors/spotify_avatar.png"


+ [ ] Donation.create package: "Bronze", amount: 1_000_00, add_vat: false, name: "CoreOS", twitter_handle: "coreos", github_handle: "coreos", display: true, gravatar_url="/img/sponsors/coreos_avatar.png"


+ [ ] Donation.create package: "Silver", amount: 2_500_00, add_vat: false, name: "Thoughtworks", twitter_handle: "Thoughtworks_de", github_handle: "https://github.com/thoughtworks", display: true, gravatar_url="/img/sponsors/thoughtworks_gravatar"

**Comment by bitboxer** [comment] 2017-03-09 22:59
Done. Everything added.

**Comment by anikalindtner** [comment] 2017-03-20 13:35
Mozilla: Donation.create package: "Silver", amount: 3_000_00, add_vat: false, name: "Mozilla", twitter_handle: "mozhacks", display: true, gravatar_url="/img/sponsors/mozilla_avatar.png"


Zalando: Donation.create package: "Silver", amount: 2_500_00, add_vat: false, name: "Zalando", twitter_handle: "zalandotech", display: true, gravatar_url="/img/sponsors/zalando_avatar.png"

**Comment by bitboxer** [comment] 2017-03-20 13:41
Okay, working on it

**Comment by bitboxer** [comment] 2017-03-20 13:45
![](https://media.giphy.com/media/xUA7aSBLwF4up8ceGs/giphy.gif)

**Comment by anikalindtner** [comment] 2017-03-20 19:38
![dancing_otter](https://cloud.githubusercontent.com/assets/1711357/24118192/346d8b0c-0dad-11e7-943e-5b96106cfad7.gif)
thank youu!

**Comment by bitboxer** [comment] 2017-03-20 19:43
🎵 When I am on my own I put on my  👑 🎤

**Comment by anikalindtner** [comment] 2017-04-13 09:47
If possible this should be done today still. SC wants to tweet about it 

+ add soundcloud Donation.create package: "Silver", amount: 2_500_00, add_vat: false, name: "SoundCloud", twitter_handle: "soundcloud", display: true, gravatar_url="/img/sponsors/soundcloud_avatar.png"

with this message in the comment field "Thanks to the organizers for all your amazing work!"

**Comment by bitboxer** [comment] 2017-04-13 09:50
Done!

**Comment by anikalindtner** [comment] 2017-04-13 12:44
And just so the campaign bar moves, even though I haven't heard back from Chris about the logo yet:

Donation.create package: "Silver", amount: 2_500_00, add_vat: false, name: "Bitcrowd", twitter_handle: "bitcrowd", github_handle: "bitcrowd", display: true

I'd point the gravatar email to info@bitcrowd.net

**Comment by bitboxer** [comment] 2017-04-13 13:47
bitcrowd added

**Comment by anikalindtner** [comment] 2017-04-14 11:02
Donation.create package: "Silver", amount: 2_500_00, add_vat: false, name: "Immobilienscout24", twitter_handle: "Immobilienscout", github_handle: "ImmobilienScout24", display: true, gravatar_url="/img/sponsors/immobilienscout_avatar.png" 

<3

**Comment by bitboxer** [comment] 2017-04-14 11:12
Done

**Comment by alicetragedy** [comment] 2018-05-07 14:53
I'm going to close this since it's from last year ;)

**Closed by alicetragedy** 2018-05-07 14:53 UTC
